// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWSa11tsQw8g9Hl32dTe7pRHFLdUdfjdc',
    appId: '1:714343640612:web:3800ee5fc9d7c1734bf2b1',
    messagingSenderId: '714343640612',
    projectId: 'myflutterauthapp-ea884',
    authDomain: 'myflutterauthapp-ea884.firebaseapp.com',
    storageBucket: 'myflutterauthapp-ea884.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfUcMhFtzHD3Brd1th3goxgb19oWiUnp8',
    appId: '1:714343640612:android:44aa86306c6fc2424bf2b1',
    messagingSenderId: '714343640612',
    projectId: 'myflutterauthapp-ea884',
    storageBucket: 'myflutterauthapp-ea884.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaCJX4n_kIK66_p4mVhto_n9H1HWTrHSc',
    appId: '1:714343640612:ios:d6ab7e2ac641891f4bf2b1',
    messagingSenderId: '714343640612',
    projectId: 'myflutterauthapp-ea884',
    storageBucket: 'myflutterauthapp-ea884.firebasestorage.app',
    iosBundleId: 'com.example.fstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaCJX4n_kIK66_p4mVhto_n9H1HWTrHSc',
    appId: '1:714343640612:ios:d6ab7e2ac641891f4bf2b1',
    messagingSenderId: '714343640612',
    projectId: 'myflutterauthapp-ea884',
    storageBucket: 'myflutterauthapp-ea884.firebasestorage.app',
    iosBundleId: 'com.example.fstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWSa11tsQw8g9Hl32dTe7pRHFLdUdfjdc',
    appId: '1:714343640612:web:67ec3d973002c80c4bf2b1',
    messagingSenderId: '714343640612',
    projectId: 'myflutterauthapp-ea884',
    authDomain: 'myflutterauthapp-ea884.firebaseapp.com',
    storageBucket: 'myflutterauthapp-ea884.firebasestorage.app',
  );
}
